import { Product } from "./types";

export const products: Product[] = [
  {
    id: "1",
    name: "Classic Cotton Tee",
    price: 29.99,
    description: "Our signature soft cotton t-shirt, perfect for everyday wear. Made from 100% organic cotton.",
    image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800",
    category: "Basic",
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["White", "Black", "Navy", "Gray"],
    inStock: true,
  },
  {
    id: "2",
    name: "Vintage Graphic Tee",
    price: 34.99,
    description: "Retro-inspired design with a modern twist. Premium quality print that won't fade.",
    image: "https://images.unsplash.com/photo-1503341455253-b2e723bb3dbb?w=800",
    category: "Graphic",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "Charcoal"],
    inStock: true,
  },
  {
    id: "3",
    name: "Athletic Performance Tee",
    price: 39.99,
    description: "Moisture-wicking fabric keeps you cool and dry during workouts. Lightweight and breathable.",
    image: "https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=800",
    category: "Athletic",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Black", "Blue", "Red"],
    inStock: true,
  },
  {
    id: "4",
    name: "Premium V-Neck",
    price: 32.99,
    description: "Elegant v-neck design with a tailored fit. Perfect for both casual and semi-formal occasions.",
    image: "https://images.unsplash.com/photo-1581655353564-df123a1eb820?w=800",
    category: "Premium",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["White", "Black", "Burgundy"],
    inStock: true,
  },
  {
    id: "5",
    name: "Eco-Friendly Hemp Tee",
    price: 44.99,
    description: "Sustainable hemp blend that's soft, durable, and environmentally conscious.",
    image: "https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=800",
    category: "Eco",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Natural", "Forest Green", "Ocean Blue"],
    inStock: true,
  },
  {
    id: "6",
    name: "Limited Edition Artist Collab",
    price: 49.99,
    description: "Exclusive design created in collaboration with local artists. Limited quantity available.",
    image: "https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=800",
    category: "Limited",
    sizes: ["S", "M", "L", "XL"],
    colors: ["White", "Black"],
    inStock: true,
  },
  {
    id: "7",
    name: "Pocket Tee Essential",
    price: 31.99,
    description: "Classic style with a functional chest pocket. Relaxed fit for ultimate comfort.",
    image: "https://images.unsplash.com/photo-1622445275463-afa2ab738c34?w=800",
    category: "Basic",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["White", "Navy", "Olive"],
    inStock: true,
  },
  {
    id: "8",
    name: "Striped Maritime Tee",
    price: 36.99,
    description: "Timeless nautical stripes with a modern cut. Breathable cotton blend.",
    image: "https://images.unsplash.com/photo-1562157873-818bc0726f68?w=800",
    category: "Pattern",
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Navy/White", "Black/White"],
    inStock: true,
  },
];